### ISSUE TITLE
Fatal error sometimes using Gutenberg blocks and PHP 8.

### ISSUE THREAD

**Issue by taneliheikkinen** [awsmin/Embed-Any-Documents#16]
I tried to upgrade my project to use PHP 8 and in some cases when the editor fetches the block data with ajax, it throws a fatal error.

Specifically in the file `awsm-embed.php` on line **179**. It throws: 
`PHP Fatal error:  Uncaught TypeError: method_exists(): Argument #1 ($object_or_class) must be of type object|string, null given`

The `get_current_screen()` function somehow returns null in some cases and that causes the fatal error. If you put a null check on that line, everything works perfectly.

**Comment by anantajitjg** [comment]
Thanks for reporting this bug and for the suggestion. This issue will be fixed in the next version of the Embed Any Document plugin.
